<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Views\Alineamientos\**" />
		<Compile Remove="Views\Modelos\**" />
		<Compile Remove="wwwroot\NewFolder\**" />
		<Content Remove="Views\Alineamientos\**" />
		<Content Remove="Views\Modelos\**" />
		<Content Remove="wwwroot\NewFolder\**" />
		<EmbeddedResource Remove="Views\Alineamientos\**" />
		<EmbeddedResource Remove="Views\Modelos\**" />
		<EmbeddedResource Remove="wwwroot\NewFolder\**" />
		<None Remove="Views\Alineamientos\**" />
		<None Remove="Views\Modelos\**" />
		<None Remove="wwwroot\NewFolder\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Mailjet.Api" Version="1.2.3" />
		<PackageReference Include="MercadoPago" Version="1.0.4477.31589" />
		<PackageReference Include="mercadopago-sdk" Version="2.3.1" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="OpenAI" Version="2.2.0" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.1" />
		<PackageReference Include="System.Windows.Extensions" Version="8.0.0" />
	</ItemGroup>
</Project>